### PR TITLE
reseting caputure image

### PR DESCRIPTION
**Pull request by iamjithinjohnson**
when camer button long press it will reset captured images

### CODE REVIEW

**Comment by Aman-zishan** [comment]
what happened. There were conflict?

**Comment by iamjithinjohnson** [comment]
aa njane github use cheyan padichu verunullo enikk doubt ind ithil whatsno indo theruooo

**Comment by Aman-zishan** [comment]
Give me your mail id ill send my number there

**Comment by iamjithinjohnson** [comment]
iamjithinjohnson@gmail.com

**Pull request closed without merging**
