### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by alirzadev**
AppBar removed 
Drawer Removed
BottomNavBar size decreased
Note: "Above changes were made so that user has more space to view and capture pic easily".

Buttons added in 2nd screen
About Screen added

### CODE REVIEW

**Comment by Aman-zishan** [comment]
> AppBar removed
> Drawer Removed
> BottomNavBar size decreased
> Note: "Above changes were made so that user has more space to view and capture pic easily".
> 
> Buttons added in 2nd screen
> About Screen added

Thanks for the contribution! can you share screenshots of the changed UI. Thanks in advance.

**Comment by alirzadev** [comment]
> > AppBar removed
> > Drawer Removed
> > BottomNavBar size decreased
> > Note: "Above changes were made so that user has more space to view and capture pic easily".
> > Buttons added in 2nd screen
> > About Screen added
> 
> Thanks for the contribution! can you share screenshots of the changed UI. Thanks in advance.

screen3

screen2
 
screen1

**Comment by Aman-zishan** [comment]
Awesome!. Thank you 😄

**Comment by Aman-zishan** [comment]
Please do check this and claim your free swag for your contribution! #14

celebrate open source ❤️ 
Happy coding ❤️

**Pull request merged**
