### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by iamjithinjohnson**
changes are done.

working perfectly 

nerthe njan pull cheythindaayirunilla my mistake

### CODE REVIEW

**Comment by Aman-zishan** [comment]
Oh thats ok, Than you for the contribution 😄 also fill out this form in #14 so that i can send you some sticker ❤️

**Comment by iamjithinjohnson** [comment]
njna github ee aduthu use cheyth thudagittullu enikk sticker enthinaan manasilayillla

**Comment by Aman-zishan** [comment]
Hacktoberfest elle, appo i have some extra laptop stickers so contributors inn ayakkamm karuthi

**Comment by iamjithinjohnson** [comment]
aa njna form fill cheythind

**Pull request merged**
