### PR TITLE
Change the gridview and make it responsive

### LINKED ISSUE #26: Enhancement -> Add mediaQuery to grid view
Add mediaquery to gridview container so that, it sizes according to different mobile view.

### PR DESCRIPTION
**Pull request by IsautierEloise**
## Description
Change the gridview method to generate a 3*3 grid, using Row and Column for a lighter and responsive solution.

## Screenshots (if appropriate):

Pixel 2 : 
Screenshot 2020-10-24 at 00 54 13

Tablet (Pixel C):
Screenshot 2020-10-24 at 00 52 45

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Doc update

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Aman-zishan** [comment]
Thank you!

**Comment by Aman-zishan** [comment]
@IsautierEloise Hey, after this merge the grayscale functionality seems to interfere with the grid view, on enabling the grid view and grayscale together the screen goes completely grey. Can you look into this :)

**Comment by IsautierEloise** [comment]
Alright I'll look into it

**Comment by IsautierEloise** [comment]
https://github.com/Aman-zishan/DocScanner/pull/31

**Pull request merged**
